import { Figtree, Black_Ops_One } from "next/font/google";
import "./globals.css";

const figtree = Figtree({
  variable: "--font-figtree-sans",
  subsets: ["latin"],
});
const blackOpsOne = Black_Ops_One({
  subsets: ["latin"], // You can add other subsets like 'latin-ext' if needed
  weight: "400", // Black Ops One only has 400 weight
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${figtree.className}`}>{children}</body>
    </html>
  );
}
